name: Copywrite Header Check

on:
  pull_request:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  copywrite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installs the copywrite CLI in PATH
      - name: Setup Copywrite
        # Pin to the latest v1 release (commit for v1.1.2 shown in docs)
        uses: hashicorp/setup-copywrite@v1.1.2

      # Validate headers without modifying files; fails if headers are missing
      - name: Validate header compliance (dry run)
        run: copywrite headers --plan
